// internal/scaffold/templates/svelte/frontend/src/App.svelte
<script>
  let status = 'Fetching...'

  async function fetchStatus() {
    // window.System_GetStatus is bound by Glyra's Go ↔ JS bridge.
    status = await window.System_GetStatus()
  }

  fetchStatus()
</script>

<main>
  <h1>{{.Title}}</h1>
  <p>Your Svelte frontend is talking to a Go backend.</p>
  <p><strong>Backend says:</strong> {status}</p>
  <button on:click={fetchStatus}>Refresh</button>
</main>

<style>
  :global(body) {
    font-family: system-ui, sans-serif;
    background: #0f172a;
    color: #e2e8f0;
    margin: 0;
  }
  main {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
  }
  h1 { color: #22d3ee; }
  button {
    margin-top: 1rem;
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 6px;
    background: #22d3ee;
    color: #0f172a;
    cursor: pointer;
  }
</style>

// internal/scaffold/templates/react-ts/frontend/src/App.tsx
import { useState } from 'react'

declare global {
  interface Window { GetSystemStatus: () => Promise<string>; }
}

function App() {
  const [status, setStatus] = useState("Waiting for Go backend...")

  const checkStatus = async () => {
    try {
      const res = await window.GetSystemStatus();
      setStatus(res);
    } catch (e) {
      setStatus("Error communicating with Go backend.");
    }
  }

  return (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', fontFamily: 'sans-serif', color: '#fafafa', background: '#09090b' }}>
      <div style={{ background: 'rgba(255,255,255,0.03)', padding: '3rem', borderRadius: '16px', textAlign: 'center', border: '1px solid rgba(255,255,255,0.1)' }}>
        <h1 style={{ margin: '0 0 1rem 0' }}>Glyra UI</h1>
        <div style={{ marginBottom: '2rem', color: '#10b981' }}>{status}</div>
        <button onClick={checkStatus} style={{ background: '#3b82f6', color: 'white', padding: '1rem 2rem', border: 'none', borderRadius: '8px', cursor: 'pointer' }}>
          Ping Go Backend
        </button>
      </div>
    </div>
  )
}

export default App
